apiVersion: v1
kind: Service
metadata:
  name: boardgame
  labels:
    app: boardgame
spec:
  type: LoadBalancer
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80        # external service port
      targetPort: 80  # matches containerPort inside the podS