apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nonso-test-monitor
  labels:
    release: prometheus   # matches your Helm release
spec:
  selector:
    matchLabels:
      app: boardgame     # must match your Service label
  namespaceSelector:
    matchNames:
      - default           # where your app is deployed
  endpoints:
  - port: http
    path: /metrics
    interval: 15s