name: Build and publish Docker image to ECR

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # optional: run on version tags

concurrency:
  group: build-and-push-ecr
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Set up Docker Buildx
      - name: Set up QEMU and Buildx (for multi-arch builds)
        uses: docker/setup-buildx-action@v2

      # 5️⃣ Build and push image to ECR
      - name: Build, tag, and push image to ECR
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: boardgame        # ✅ Change this if needed
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail

          echo "🔹 Starting ECR build and push pipeline..."

          # Resolve AWS Account ID if not provided
          if [ -z "${AWS_ACCOUNT_ID:-}" ] || [ "${AWS_ACCOUNT_ID}" = "null" ]; then
            echo "⚠️ AWS_ACCOUNT_ID secret not set — attempting to retrieve via STS..."
            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          fi
          echo "✅ Using AWS Account ID: ${AWS_ACCOUNT_ID}"

          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          echo "✅ Using ECR registry: ${ECR_REGISTRY}"
          echo "✅ Using repository: ${ECR_REPOSITORY}"

          # Create repository if missing
          if ! aws ecr describe-repositories --repository-names "${ECR_REPOSITORY}" >/dev/null 2>&1; then
            echo "📦 Repository ${ECR_REPOSITORY} not found — creating..."
            aws ecr create-repository --repository-name "${ECR_REPOSITORY}" >/dev/null
          fi

          # Build and push Docker image
          echo "🚀 Building Docker image..."
          docker buildx build \
            --platform linux/amd64 \
            -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} \
            -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest \
            --push .

          echo "✅ Image pushed to ECR: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

      # 6️⃣ Run vulnerability scan (warning only)
      - name: Scan image for vulnerabilities (Trivy)
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: boardgame
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set +e  # do not fail on non-zero exit
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

          echo "🔍 Running Trivy vulnerability scan (HIGH, CRITICAL only)..."
          docker run --rm aquasec/trivy:0.43.1 image \
            --format table \
            --severity HIGH,CRITICAL \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} || \
            echo "⚠️ Trivy detected HIGH/CRITICAL vulnerabilities (warning only, build will continue)."

          echo "✅ Trivy scan complete — warnings (if any) were logged, but build succeeded."
